version: "2.1"
services:
  cli:
    environment:
      SELENIUM_BROWSER_NAME: ${SELENIUM_BROWSER_NAME}
      SELENIUM_DEBUG: ${SELENIUM_DEBUG}
  selenium:
    image: selenium/standalone-${SELENIUM_BROWSER_NAME}${SELENIUM_DEBUG}
    expose:
      - 4444
    environment:
      - TZ=${SELENIUM_TIMEZONE}
      - GRID_TIMEOUT=90
      - SCREEN_WIDTH=${SELENIUM_SCREEN_WIDTH:-1366}
      - SCREEN_HEIGHT=${SELENIUM_SCREEN_HEIGHT:-768}
      - SCREEN_DEPTH=${SELENIUM_SCREEN_DEPTH:-24}
      - SCREEN_DPI=${SELENIUM_SCREEN_DPI:-74}
    ports:
      - ${SELENIUM_PORT:-4444}:4444
      - ${SELENIUM_VNC_PORT:-5900}:5900
