version: "2.1"
services:
  cli:
    environment:
      SELENIUM_STANDALONE_BROWSER: ${SELENIUM_STANDALONE_BROWSER}
      APPLICATION_BASE_URL: ${APPLICATION_BASE_URL}
      APPLICATION_ADMIN_USER: ${APPLICATION_ADMIN_USER}
      APPLICATION_ADMIN_PASS: ${APPLICATION_ADMIN_PASS}
      APPLICATION_FRONT_USER: ${APPLICATION_FRONT_USER}
      APPLICATION_FRONT_PASS: ${APPLICATION_FRONT_PASS}
      APPLICATION_ADMIN_LOGIN_URL_PATH: ${APPLICATION_ADMIN_LOGIN_URL_PATH}
      APPLICATION_ADMIN_WEBINAR_NEW_URL_PATH: ${APPLICATION_ADMIN_WEBINAR_NEW_URL_PATH}
      APPLICATION_USER_LOGIN_URL_PATH: ${APPLICATION_USER_LOGIN_URL_PATH}
      APPLICATION_USER_LOGOUT_URL_PATH: ${APPLICATION_USER_LOGOUT_URL_PATH}
      APPLICATION_WEBINAR_FUTURE_URL_PATH: ${APPLICATION_WEBINAR_FUTURE_URL_PATH}
      APPLICATION_WEBINAR_PAST_URL_PATH: ${APPLICATION_WEBINAR_PAST_URL_PATH}
  selenium:
    image: selenium/standalone-${SELENIUM_STANDALONE_BROWSER}
    expose:
      - 4444
    environment:
      - TZ=${SELENIUM_TIMEZONE}
      - GRID_TIMEOUT=90
    ports:
      - ${SELENIUM_PORT:-4444}:4444
      - ${SELENIUM_VNC_PORT:-5900}:5900
