#!/usr/bin/env bash

### Preview tests via VNC

if type open >/dev/null 2>&1; then
    echo "Opening VNC connection to 127.0.0.1:${SELENIUM_VNC_PORT:-5900}."
    open vnc://127.0.0.1:"${SELENIUM_VNC_PORT:-5900}"
    echo "Please type 'secret' as password."
else
    echo "Open VNC connection to 127.0.0.1:${SELENIUM_VNC_PORT:-5900} and type 'secret' as password."
fi
