#!/usr/bin/env bash

#: exec_target = cli

## Execute behat tests on Selenium
##
## Read more on https://www.kaliop.pl/Blog/Artykuly/Testy-automatyczne-wprowadzenie-Behat-Selenium-Mink

cd ${PROJECT_ROOT}
bash .docksal/commands/check
if [[ "$?" == "0" ]]; then
    php vendor/bin/behat -p ${SELENIUM_BROWSER_NAME} $@
fi
